<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="types" nsURI="http://www.spp.org/cocome/types/Types" nsPrefix="types">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//ComplexType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//Type #//DeclarationTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapType" eSuperTypes="#//Type #//DeclarationTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapType" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclarationTypeReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference" eSuperTypes="#//DeclarationTypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//NamedType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//NamedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ComplexType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationType" eSuperTypes="#//ComplexType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityType" eSuperTypes="#//ComplexType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageModifier" eType="#//TypeStorageModifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeStorageModifier">
    <eLiterals name="STORABLE" literal=" storable"/>
    <eLiterals name="EMBEDDABLE" value="1" literal="embeddable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageModifier" eType="#//PropertyStorageModifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DeclarationTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationship" eType="#//EntityRelationship"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderBy" eType="#//PropertyReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapKey" eType="#//PropertyReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literal" eType="#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//EntityRelationshipKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedBy" eType="#//MappedByReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EntityRelationshipKind">
    <eLiterals name="UNIQUE" literal="unique"/>
    <eLiterals name="MANY" value="1" literal="many"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappedByReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//MappedByReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyStorageModifier">
    <eLiterals name="VARIABLE" literal="var"/>
    <eLiterals name="VALUE" value="1" literal="val"/>
    <eLiterals name="TRANSIENT" value="2" literal="transient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyReference" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Property"/>
  </eClassifiers>
</ecore:EPackage>
