/**
 * generated by Xtext
 */
package org.spp.cocome.types.ui.contentassist;

import org.spp.cocome.types.ui.contentassist.AbstractTypesProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class TypesProposalProvider extends AbstractTypesProposalProvider {
}
