/**
 * generated by Xtext
 */
package org.spp.cocome.types.validation;

import org.spp.cocome.types.validation.AbstractTypesValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class TypesValidator extends AbstractTypesValidator {
}
