/*
* generated by Xtext
*/
package org.spp.cocome.types;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TypesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.spp.cocome.types.ui.internal.TypesActivator.getInstance().getInjector("org.spp.cocome.types.Types");
	}
	
}
