/*
 * generated by Xtext
 */
package org.spp.cocome.types.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.spp.cocome.types.ui.internal.TypesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TypesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TypesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TypesActivator.getInstance().getInjector(TypesActivator.ORG_SPP_COCOME_TYPES_TYPES);
	}
	
}
