/*
* generated by Xtext
*/
package org.spp.cocome.types;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TypesStandaloneSetup extends TypesStandaloneSetupGenerated{

	public static void doSetup() {
		new TypesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

