/*
 * generated by Xtext
 */
package org.spp.cocome.types;

import org.spp.cocome.types.typing.TypeGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TypesRuntimeModule extends org.spp.cocome.types.AbstractTypesRuntimeModule {
	/**
	 * {@inheritDoc}<br>
	 * This extension registers the custom {@link TypeGlobalScopeProvider} that realizes e.g. the
	 * correct linking of primitive data types. The implementation of that part is broadly transfered
	 * from the JVMTypes binding.
	 */
	@Override
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return TypeGlobalScopeProvider.class;
	}
}
